### ISSUE TITLE
Breakfast recipe

### ISSUE THREAD

**Issue by lbisinoto** [IntroToCode/RecipesCodemates7#1]
## 💬 Discussion topic

How to separate the work

## ❗ Potential issues

- Everyone doing different recipes
- Having different ideas of how to cook something

## 👥 People to consult

@gdempse @nohanoweir @nohanoweir 

## 📃 Details

Coming up with work division to increase efficiency

**Comment by nohanoweir** [comment]
Noha - create pull request for banana pancake recipe 
Greg - close issue after being resolved
Chukwunale - approve pull request and star

**Comment by gdempse** [comment]
We merged this already? I don't think we hit all of the points we needed.

**Comment by gdempse** [comment]
acceptance criteria?

**Comment by lbisinoto** [comment]
we merged but can continue to merge as the commits come in. as for the other two, acceptance criteria should include what we have in our assignment in bcourses. I believe we have still someone missing to contribute to this recipe to be able to accept a full merge to the main branch, right?

**Comment by cakpati** [comment]
All good with breakfast. Closing out this issue.
